### ISSUE TITLE
Export as Arduino Sketch fails

### ISSUE THREAD

**Issue by DocCleaner** [bromagosa/Snap4Arduino#104]
I started a new arduino translatable project in Snap4Arduino 1.2.1 win 64, created a very simple program and tried to export it. Snap4Arduino just gives me an error messagge "Cannot read property 'toString' of null".

The simple project is attached, so is a screen capture of the error message.

[ExportTest.zip](https://github.com/bromagosa/Snap4Arduino/files/628811/ExportTest.zip)

![errormessage](https://cloud.githubusercontent.com/assets/24353768/20859007/cb4a858e-b952-11e6-93c1-c08940c30290.PNG)

**Comment by jguille2** [comment]
Hi @DocCleaner,

The problem is in the second **set digital pin _x_ to _y_** block. _y_ value must be a boolean, and in your script is empty (lika a string)

You must change your
![setdigitalempty](https://cloud.githubusercontent.com/assets/2926315/20866273/d0987032-ba29-11e6-9123-d02fe9ea87fd.png)
for
![setdigitalfalse](https://cloud.githubusercontent.com/assets/2926315/20866276/d6e65e54-ba29-11e6-984c-d7f451e9eec9.png)
And this is all.

Joan

**Comment by DocCleaner** [comment]
Hi @jguille2 ,

thank you for the quick answer!
I'm a little embarrassed, but this solves my problem.
I tested the original script with a transitor and LED connected and it switched the LED on and off, so I thought my setting was the FALSE setting. (I'm just starting with snap...)

Thanks again,
Sven
