### ISSUE TITLE
<digital reading _> turning off digital pin?

### ISSUE THREAD

**Issue by Smtih** [bromagosa/Snap4Arduino#111]
When trying to read a digital pins state it turns that digital pin off? I assume this is not the intended behaviour?

**Comment by jguille2** [comment]
Yes,
When I read a digital pin, this pin turns to Input mode. Then, if i connect no sensor, I will see 0V (low), because is not a Pull_up mode (is an standard input).
Is this your question?

Joan

**Comment by Smtih** [comment]
I'm not sure. I have an LED connected to a pin (say pin 10)
If I do
[Set Digital Pin (10) to \<true>] (The LED turns on)
<digital reading (10) > (Gives back true, but the LED then turns off)

**Comment by jguille2** [comment]
I try to explain...

You turn pin 10 to true (high). Led turns on. You do a digital reading on 10. Led turns off... so 10 is low (false). But you have a true reading! Yes, but only the first reading. If you take another reading, you'll see false (low).

It's the normal behaviour, because this processes are asychronous. We can say "your first reading of a true state, change this state itself to false", and so the reading is of the state before. I any case, first reading of asynchronous processes may be wrong. This is a  firmata behaviour. The first reading actives the reporting and so, its first reading maybe wrong (only the first!!!)

Joan
