### ISSUE TITLE
Android application for KitKat version

### ISSUE THREAD

**Issue by rhlgupta** [bromagosa/Snap4Arduino#130]
Please help me build an Android application of Snap4Arduino for Android KitKat version. I build Snap4arduino using your documentation but it is working on android 5 and above versions only.

**Comment by bromagosa** [comment]
Hi @rhlgupta,

the Android version is not ready for end-users at all, it's still in active development and I don't expect a beta release to come out before May. I wouldn't recommend using it to anyone for anything more than trying it out at home, or helping me with development ;)

I'm working on an Android 5 tablet at the moment, that's why the build system creates an APK for this version. I guess to build for an older OS you'd have to play around with the platform name at `src/platforms/mobile/android/build`, line 23:

`cordova platform add android@5.2.2`

I can't guarantee this alone would work though, it's possible that the Cordova plugin for serial over Blueetooth would need to be rebuilt for Android 4.

Anyway, when I get closer to releasing I'll start playing with building for older versions, as it's true that there are still many Android 4 devices around.

Cheers,
Bernat.

**Comment by rhlgupta** [comment]
Hi @bromagosa 

Thank you for response. I will be happy to contribute in development of Snap4Arduino.

And can you please tell me where to add my blocks and projects xml code in snap4aduino. So that when I build application, it is permanently registered there.
