### ISSUE TITLE
Sync LED blinking

### ISSUE THREAD

**Issue by DenysZaytsev** [bromagosa/Snap4Arduino#174]
Hi Guys,

Is there a way to make LEDs on different PINs to blink in sync (with 0.5-1 seconds delay)?
Those should be triggered by pressing single button.
If so - can you help me to do it please?

**Comment by jguille2** [comment]
Hi,
You can do this in different ways. But sometimes, real world is "worse" than virtual one :angry: ... and you may have different issues and get (maybe not) an imperfect sync (because electronics...).

At first, you have two options: sequencing the actions (and maybe not even see the wait between consecutive actions) or trying to program actions in parallel.
First option:
![seqblink](https://user-images.githubusercontent.com/2926315/28080904-d44c13dc-666d-11e7-8094-3238bf8b51d9.png)

Second options:
![parallelblink](https://user-images.githubusercontent.com/2926315/28081074-55e13936-666e-11e7-955d-9eefcf6befc0.png)

And many other options. For example, if there are many leds you can simplify the code ...
![multiplepins](https://user-images.githubusercontent.com/2926315/28081307-17152220-666f-11e7-8af0-b7055e282312.png)

And more... using lists...

Joan
