### ISSUE TITLE
"connot talk to arduino in undefined port" when I used it via wifi

### ISSUE THREAD

**Issue by duyaTech** [bromagosa/Snap4Arduino#224]
as shown in this picture:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/31816340/35205679-150b4c74-ff72-11e7-9391-4ec08d41517f.png">

**Comment by jguille2** [comment]
Hi!
Finally yesterday I got a ESP8266 module!!

And the first thing I done, of course, was to build a wifi connection between Snap4Arduino and an UNO board. And it went fine!!!

About this issue, they can be different things. A try to point some details:

- I guess StandardFirmata is load into the UNO.

- Be sure you disconnected the [GPIO 0 - Ground] connection after pushing the "WifiToSerial Sketch. You must do this bridge for programming the ESP, and release it to normal operation.
Maybe your module has a switch to do this (Program <-> UART).

- You can edit two params of the Sketch (maybe we'll edit the template... after more testing):

  - Line 49 `int    baudRate       = 115200;`. Change `115200`to `57600`
  Yes! You can edit this before with your browser (the config page of the ESP server) but you will have to change always. And the browser cache can fool you and show 57600 but it was not the real value. My hypothesis is your problem is here.

  - Line 50 `String mDNS           = "esp8266";` Change `esp8266` to `arduino`
  You can write another name, but 'arduino' is the default value. And in Snap4Arduino 1.2.4 there is a bug that the system can not change it. This is fixed into the master dev for the next release... but putting 'arduino', you can work it out (the address will be'tcp://arduino.local:23'.

Is this helpful?

Joan

**Comment by duyaTech** [comment]
Hi, there. 
      Thank you for telling me so many details. I've already changed the hostname into 'arduino.local' due to some bugs in the latest compiled version yesterday. And I will take it a shot immediately according to your suggestion. Thank you again for your kindness. @jguille2

**Comment by duyaTech** [comment]
Looks like it's a nice shoot. You just hit the point. So the key point is the baudrate. Thank you again, deeply. @jguille2

**Comment by jguille2** [comment]
Ok @xia01eng . I close this issue.

As I said, until yesterday I had not been able to test 'network port' operation. I want to test a little more... and I add two lines to my (too long) TODO list.
  - Update wiki documentation of "wifi serial" adding details and updating the sketch to do it easier.
  - Explore if we can add "network port" operation to the online version (chromium).
Joan
