### ISSUE TITLE
Why does the web version download have so many costumes, backgrounds, and sounds?

### ISSUE THREAD

**Issue by ToonTalk** [bromagosa/Snap4Arduino#238]
When I downloaded https://github.com/bromagosa/Snap4Arduino/releases/download/1.2.5/Snap4Arduino_web-chromium_1.2.5.zip

I find over 100 backgrounds, 700 costumes, and over 200 sounds. But it is not clear if there is an interface for accessing them from within Snap4Arduiono.

**Comment by jguille2** [comment]
Hi Ken @ToonTalk 

This is not an Snap4Arduino issue. This is just Snap! code. For example, at Snap site, you can see 103 [Snap Backgrounds files](https://snap.berkeley.edu/snapsource/Backgrounds/) but only 12 [Snap Backgrounds catalogued](https://snap.berkeley.edu/snapsource/Backgrounds/BACKGROUNDS). 

And also, this Snap issue, is into my TODO list. You know we had (in Snap4Arduino 1.2.4) a Snap modification with a Costumes/Backgrounds categorization. We have left it, because it was more sustainable to be aligned with Snap in this aspect.

Then, we try to implement that categorization (needed because there are already many images) inside Snap itself. And then, we will found out what happens with all these pictures... and what pictures must be available in the catalog.
