### ISSUE TITLE
Chrome/Chromium plugin not getting added into Chrome extensions

### ISSUE THREAD

**Issue by rahulswaminathan** [bromagosa/Snap4Arduino#263]
Hi,

Firstly, I'd like to thank you guys for Snap4Arduino! Awesome integration with hardware!

I've been using the OSX desktop version which works seamlessly with Arduino based boards. Recently, 
I've been trying to get the Chrome/Chromium plugin installed on Chrome (v69.0.3497.100). It's the latest stable version of Chrome. I've followed the procedure on the website i.e. to drag and drop the crx file on chrome://extensions page but it keeps giving the below message:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/11411435/46096690-759da900-c1dd-11e8-9f28-427066dd0c8b.png">

I've tried this on Windows 10 and MacOS High Sierra with both versions of the plugin i.e. 1.2.6 and 1.2.5. I've also tried to install it using the zip file mentioned in #178 issue.

Am I missing something in the installation procedure?

**Comment by bromagosa** [comment]
Hi @rahulswaminathan.

The plugin is, because of a new policy by @GoogleChrome, no longer installable on desktop computers. They took this away without giving us any options whatsoever to access the serial port from a website. It is now humanly impossible to do realtime interaction with a serial device from a website.

There is a hack that circumvents this policy for the time being, but since they keep changing their policies without offering alternatives we can't be sure how long it will work. We're studying what to do.

Sorry about that :(

Thanks, @GoogleChrome.

**Comment by jguille2** [comment]
Hi @rahulswaminathan 

Sorry for this unclosed old issue. I have to check all these unclosed issues to show clearly what's still open.

I only post here guessing you know Snap4Arduino still has (and running properly) a Chrome/Chromium/Edge plugin to use Snap4Arduino with [our online version](http://snap4arduino.rocks/run). This has an [easy installation on Chromebooks](https://chrome.google.com/webstore/detail/snap4arduino-connector/fhmkennllhhclkcjcdaegceilcefedle), and it's fully operational on Chrome/Chromium/Edge browsers, just [downloading it](https://github.com/bromagosa/Snap4Arduino/releases/download/7.0.4/Snap4Arduino_web_connector_crx_7.0.zip) and [using de "developer mode" under extensions](http://snap4arduino.rocks/#install).

**Comment by rahulswaminathan** [comment]
Thanks @jguille2!
