### ISSUE TITLE
Wrong "Scale between ranges" block in library.

### ISSUE THREAD

**Issue by DavidGasku** [bromagosa/Snap4Arduino#271]
The block "Scale from range () to range ()" is wrong, as you can see in the picture.
![graph calculator 4 script pic](https://user-images.githubusercontent.com/5382201/48933993-9561fc80-ef02-11e8-9b4f-9fd70f288641.png)

The formula should be:
![graph calculator 4 script pic 1](https://user-images.githubusercontent.com/5382201/48933992-9561fc80-ef02-11e8-9911-d2a8a55757a9.png)

If it is updated, I would recommend these two blocks:

- This block just constrain one value to a range:
![graph calculator 4 script pic 3](https://user-images.githubusercontent.com/5382201/48933990-94c96600-ef02-11e8-99d5-4001dbb54762.png)

- A modified version of scale (especially useful while working with analog sensors) constrained to the output range:
![graph calculator 4 script pic 2](https://user-images.githubusercontent.com/5382201/48933991-94c96600-ef02-11e8-9d5d-402acf58a819.png)
![graph calculator 4 script pic 4](https://user-images.githubusercontent.com/5382201/48933989-94c96600-ef02-11e8-94df-8b0775a851bf.png)

Here you have the three blocks, in case you want to update the library:

[scale blocks.zip](https://github.com/bromagosa/Snap4Arduino/files/2610105/scale.blocks.zip)

**Comment by DavidGasku** [comment]
Great, that's better.

**Comment by jguille2** [comment]
Hi,
This fix it's easy. But we know libraries have a difficult maintenance (custom blocks definitions are stored inside the projects). So, to avoid further modifications, we must think better.

I saw the proposed block was too long and also, constrained boolean slot was not more elegant. So I propose a shorter block, using "over the range" for a non-constrained behavior and "into the range" for a constrained.

My proposal is two blocks (scale and constrain). Details:

- The **scale block**
![scaleblock](https://user-images.githubusercontent.com/2926315/49068708-b9d21780-f227-11e8-83d4-e5a1f843fcb9.png)
with this definition:
![scaledef](https://user-images.githubusercontent.com/2926315/49068736-c8b8ca00-f227-11e8-91ca-1b69626317a9.png)
In this block, **over** references the target range and the result is not constrained to this range. And **into** also references the target range, but here the result is constrained.
Note that we can change the "gradient" because the block accepts "reverse ranges".
![scaleover](https://user-images.githubusercontent.com/2926315/49068958-5e545980-f228-11e8-8807-955fdea59030.png)
![scaleinto](https://user-images.githubusercontent.com/2926315/49068966-644a3a80-f228-11e8-9872-d3c74ed4d281.png)

- And the **constrain block**
![constrainblock](https://user-images.githubusercontent.com/2926315/49068999-7d52eb80-f228-11e8-80e5-6bb47b15d73f.png)
where the order of the range inputs does not affect to the result (they are the endpoints, not max a min)
![constraindef](https://user-images.githubusercontent.com/2926315/49069150-d589ed80-f228-11e8-9793-2ee483971e27.png)

Waiting for your opinions (@bromagosa, and also @DavidGasku )

Joan

**Comment by bromagosa** [comment]
I don't understand the "over" and "into" options, but otherwise `constrain` and `scale` look good to me.

**Comment by jguille2** [comment]
Maybe are wrong expressions... Then I need your opinion.

The idea was:

"scale 6 from [0,5] over [5,10]" will report 11 (scaling without constraining) and

"scale 6 from [0,5] into [5,10]" will report 10 (scaling and constraining)

**Comment by bromagosa** [comment]
I see! I'm not sure "over" and "into" are the right words then. If I got it right, one of them (into) caps values outside the range to the range limit, and the other one (over) sort of applies "mod" to them, is that correct?

I can't think of a single use case for the second option, so I'd suggest always capping values into the range. A value that's outside the original range is an illegal value, so what to do with it is an arbitrary matter, isn't it?

"Give me the fourth element of this list of three elements" has multiple answers, but I'd expect the language to say "there's no fourth element" :)

**Comment by jguille2** [comment]
To force constraining is not bad... but I think keeping this two options (constraining and no-constraining) is also good.

I note (I know this is the most important argument) that people coming from Arduino IDE, are using a _map_ function (useful for example working with sensor values) and that _map_ function is not constraining (the reference says "MAP does not constrain values to within the range, because out-of-range values are sometimes intended and useful. The constrain() function may be used either before or after this function, if limits to the ranges are desired.")

We can think about this. We must decide if we want one or two options and, if we choose two options, think about the best words.

We can use "scale value from [a,b] constrained/not constrained to [c,d]"  (where constrained/not constrained are dropdown options). Maybe this is more clear that "into/over". But, if "into/over" was "sufficiently understandable", I think it would be a more beatiful option.

**Comment by bromagosa** [comment]
Okay, I see. I didn't understand the need to have this lib in the first place, since you can scale things yourself by using addition, subtraction, division and multiplication (should we add a "mean" block too? and a max block? and a min block? these are all things you're encouraged to write yourself), but since the only reason to have it was that people coming from the Arduino framework missed it, we should probably stick with what the Arduino libs do and have two blocks: `scale` (unconstrained) and `constrain`. Don't you think so?

**Comment by jguille2** [comment]
I agree.
So, two questions...

- Delete this scale lib or keep it and fix the wrong behavior?

- If we keep it (then unconstrained) we can keep the original block
![scale1](https://user-images.githubusercontent.com/2926315/49144471-c5900d80-f2fd-11e8-96d4-04a30f41f915.png)

  or change it to a shorter form?
![scale2](https://user-images.githubusercontent.com/2926315/49144484-ccb71b80-f2fd-11e8-8e7a-7b268efefaa2.png)

Finishing... @bromagosa make the decision... and I'll update the changes.

**Comment by bromagosa** [comment]
Let's keep the lib and fix it. Choose the version you like the most :)

**Comment by jguille2** [comment]
Done!

Fixed with [this commit](https://github.com/bromagosa/Snap4Arduino/commit/f0fd4ed6f9acf38accf93ae479f69f45e2e24e56). Finally I've chosen the shorter form. So, projects with "scale - from range - to range -" have the wrong (unfixed) block.

Thanks @DavidGasku for your report!

Joan
