### ISSUE TITLE
Text to Speech and Misc

### ISSUE THREAD

**Issue by danadak** [bromagosa/Snap4Arduino#286]
When I use it in a simple loop reading Arduino A/D and speaking
the value several things do not work quite right -

![image](https://user-images.githubusercontent.com/12602329/61998981-20912480-b086-11e9-9a68-98168471bf7a.png)

1) Cannot stop or kill the main loop with the "when key is pressed" block. I have
to exit Sanp4Arduino to kill the process.

2) In sprite window the variable holding the Arduino A/D reading does not update.
However if I put a "pause" at end of forever loop each time I loop it again by clicking
the pause block it does update the variable in the sprite window.

3) I cannot click a project file  in some fashion to find out where it is located, eg. its path.

4) I cannot add a comment to a block, like in Ardublock, mBlock....

Running 1.2.7 version on Win 10, UNO board.

Love the application, supurb tool for beginner and experienced.

Regards, Dana.

**Comment by jguille2** [comment]
Hi Dana (@danadak )

Excuse our delay... but holidays have forgotten your issue :(

The problem here is you must use the block "speak .... **and wait**"". Without "**wait**" the script (the loop) keeps running before it is spoken. Then, you make a long queue (that grows continuously) and then the browser crashs.

So, change that block and it will run ok.

Joan
