### ISSUE TITLE
http://ip:42001/stage

### ISSUE THREAD

**Issue by raffoux** [bromagosa/Snap4Arduino#303]
Hello, 
The http://ip:42001/stage command no longer works with version 6.  I use the GNU/linux version (64 bits).
Thank you.
Jean-Christophe

**Comment by jguille2** [comment]
Oops!!

I'm sorry, @raffoux. You are right. And `stageimg` is also KO. :disappointed: 

We used `fullImageClassic()` Snap! function, but it is not available in Snap!6.

I will fix this, and I will release a new minor version to publish it. I will announce it here.

Thanks for reporting it.

Joan

**Comment by jguille2** [comment]
Oh...This issue has been lost for a lot of time :(
Sorry, @raffoux 
I'm sure you must not be tracking it anymore... but I close the issue because I've fixed today (https://github.com/bromagosa/Snap4Arduino/commit/7023dbfd7ded6e7075c6ef4057f535a4b09f32fb) that issue. It will be released into he next Snap4Arduino 9 (before Christmas).

Thanks for reporting.
Joan

**Comment by raffoux** [comment]
Hello, that's very good. It's a great addition to the software. Thanks again for your work.
Jean-Christophe
