### ISSUE TITLE
Error generate from source

### ISSUE THREAD

**Issue by villecaribas** [bromagosa/Snap4Arduino#319]
### Error generate from source
After instal Ubuntu Linux 22.4

``$ sudo apt-get install node npm sed zip unzip git wget``

I have execulte commands

`./prepare --all
`
after that

`./build --platform=desktop/win/64`

```
nothing works and get this message:
=======
Setting version name...
=======


=======
Asking nwbuilder to build Snap4Arduino for linux64
=======

src/platforms/desktop/gnu/64/build: 36: environments/node_modules/nw-builder/bin/nwbuild: not found
mv: cannot stat 'releases/desktop/Snap4Arduino/linux64/*': No such file or directory
desktop/gnu/64

=======
Renaming executable...
=======

mv: cannot stat 'releases/desktop/gnu/64/Snap4Arduino': No such file or directory

=======
Copying icon files over...
=======


=======
Copying desktop entry over...
=======

Removing temporary files...
Copying license file over...
Done!
```
Anyone know tell me to solve this problem?

**Comment by jguille2** [comment]
Hi @villecaribas 

I think your problem is with the `nw-builder` module.

This module changed their queries in the last versions... and I didn't want to maintain different scripts depending on which version the developer is using.
I wrote down this note to remember this possible issue
https://github.com/bromagosa/Snap4Arduino/blob/master/prepare#L52

So, my suggestion is to downgrade nw-builder to 3.5.7
Other option is go to https://github.com/bromagosa/Snap4Arduino/blob/master/src/platforms/desktop/build#L36 and update the way that command (nw-builder) is running with your current (or custom) nw-builder version.

Joan

**Comment by villecaribas** [comment]
I''ll do that. Tks!!

**Comment by villecaribas** [comment]
TKS
to work for me I had to do this

`$ sudo apt-get install node npm sed zip unzip git wget`
`$ ./prepare --all`
`$ ./prepare --inno`
`$ cd environments`
`$ npm uninstall nw-builder`
`$ npm install nw-builder@3.5.7`
`$ cd ..`
`$ ./build --platform=desktop/win/64 --makeinstaller`

:-)
TKS @jguille2
