### ISSUE TITLE
Translatable Projects Broken Since 6.2

### ISSUE THREAD

**Issue by dragazo** [bromagosa/Snap4Arduino#325]
When opening the online editor, everything works fine, but if I switch to an Arduino translatable project, there are now a bunch of javascript errors in the console, the block palette categories look messed up (some like Control are missing unless it was the selected category prior to switching to translatable mode, in which case the category is still missing, but you can see the blocks that _should_ be there), and I cannot create custom blocks (in any category). I tried downloading each desktop release going backwards in time, and the latest one that worked was the 6.2 release. All releases after that appear to have errors when switching to translatable mode.

**Comment by jguille2** [comment]
Hi Devin @dragazo 

Yes, you are right :(

I hadn't seen it.
We implemented this functionality because some people found it useful (I guess not many, because this is the first report of the problem... and I see it's really old!) but we never saw it clearly (it might seem useful in some cases... but it's not the purpose of Snap4Arduino... and it can't provide it in a consistent way either because we can't translate to "arduino code" the way of a dynamic environment like Snap!)

But obviously, we have to decide whether to remove it permanently or fix it!

Thanks for the warning. We think we do for the next version.

In case it's useful for you, just comment that we have previous versions uploaded.. and therefore, you can use the functionality quickly from
https://snap4arduino.rocks/v6/#

Joan

**Comment by jguille2** [comment]
Hi Devin @dragazo

Although the translation mode in Arduino is still an experimental and non-strategic feature for Snap4Arduino project, I have fixed it today (https://github.com/bromagosa/Snap4Arduino/commit/1b48370f6c2d6adb74a446e002af87f04967be53) so that it remains operational.
The feature is just the same it was... but the IDE integration is better, because now Snap! itself auto "hide" empty categories.

It will be available with Snap4Arduino 9 release, which I want to get out before Christmas.

Thanks for your report!
Joan
